### ISSUE TITLE
android.os.DeadObjectException found on crashalaytics 

### ISSUE THREAD

**Issue by chris-joseph** [lschmierer/android_play_install_referrer#13]
Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:575)
       at com.google.android.a.a.a(a.java:8)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a(IGetInstallReferrerService.java:7)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:26)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.a(AndroidPlayInstallReferrerPlugin.java:38)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:25)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2067)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2099)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

[https://drive.google.com/file/d/1U1QjgoMl9yknxeG2Hi__kbSIWGySOyEv/view?usp=sharing](url)

**Comment by lschmierer** [comment]
This seems to be an issue within Android or Google's Install Referrer library. Not directly related with this plugin.

Can you provide a minimal example, favorably in a Git repository?

**Comment by geek2driod** [comment]
I am also facing the same issue.

**Comment by lschmierer** [comment]
Im gonna close this for now, as you were not able to provide additional information.

**Comment by slorop41314** [comment]
Also facing this issue.

<img width="1118" alt="Screen Shot 2021-07-19 at 08 56 19" src="https://user-images.githubusercontent.com/52713279/126092045-5f524cf8-69a3-4fd5-bf63-d87052091a36.png">
