### ISSUE TITLE
Dead Object Exception

### ISSUE THREAD

**Issue by sharansingh00002** [lschmierer/android_play_install_referrer#21]
Getting a dead object exception

```
android.os.DeadObjectException: null
    at android.os.BinderProxy.transactNative(BinderProxy.java)
    at android.os.BinderProxy.transact(BinderProxy.java:545)
    at com.google.android.a.a.b(BaseProxy.java:2)
    at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c(IGetInstallReferrerService.java:3)
    at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:5)
    at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.handleOnInstallReferrerSetupFinished(AndroidPlayInstallReferrerPlugin.kt:86)
    at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.access$handleOnInstallReferrerSetupFinished(AndroidPlayInstallReferrerPlugin.kt:17)
    at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.onInstallReferrerSetupFinished(AndroidPlayInstallReferrerPlugin.kt:72)
    at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:4)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2022)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2054)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7950)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by ardakazanci-mobven** [comment]
did you find a solution?

**Comment by noinskit** [comment]
I'm also hitting this, with nearly identical stack traces.

**Comment by lschmierer** [comment]
How often and under what circumstances do you get this error? Is the app e.g. in background? Or do you call `await AndroidPlayInstallReferrer.installReferrer` multiple times?

**Comment by Ruslan660** [comment]
Also hitting this in crashlytics
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/43512060/176416068-95f55d5b-78e6-4bb5-8774-afe52ea004b6.png">

**Comment by atrope** [comment]
We are Having the same crash:
```
java.lang.RuntimeException: 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:612)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: android.os.DeadObjectException: 
  at android.os.BinderProxy.transactNative (Native Method)
  at android.os.BinderProxy.transact (BinderProxy.java:605)
  at com.google.android.a.a.b (BaseProxy.java:2)
  at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c (IGetInstallReferrerService.java:3)
  at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:1)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.kt:85)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.access$handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.kt:17)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.onInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.kt:72)
  at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java:4)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:2084)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:2116)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8645)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```


All OS:
![Screen Shot 2022-08-01 at 11 18 31](https://user-images.githubusercontent.com/2945478/182168437-29018857-87e1-4217-960e-f63a75829204.png)

**Comment by atrope** [comment]
@lschmierer We only call once in the app lifetime. In main.dart.



```
 if (Platform.isAndroid) {
    final isFirstRun = await _getFirstRun();
    if (isFirstRun) {
      final referrerDetails = await AndroidPlayInstallReferrer.installReferrer;
      if (referrerDetails.installReferrer != null) {
        final ref = referrerDetails.installReferrer;
      }
    }
  }
```

First run checks if has local storage key.

**Comment by prasad-anecure** [comment]
`Caused by android.os.DeadObjectException:
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:571)
       at com.google.android.a.a.android.os.Parcel b(android.os.Parcel)(:8)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.android.os.Bundle c(android.os.Bundle)(:7)
       at com.android.installreferrer.api.InstallReferrerClientImpl.com.android.installreferrer.api.ReferrerDetails getInstallReferrer()(:26)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.void handleOnInstallReferrerSetupFinished(int)(:76)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.void access$handleOnInstallReferrerSetupFinished(de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin,int)()
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.void onInstallReferrerSetupFinished(int)(:2)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(:25)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2096)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2129)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:231)
       at android.os.Looper.loop(Looper.java:338)
       at android.app.ActivityThread.main(ActivityThread.java:8065)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:579)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)`

**Comment by prasad-anecure** [comment]
```
Caused by android.os.DeadObjectException:
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:571)
       at com.google.android.a.a.android.os.Parcel b(android.os.Parcel)(:8)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.android.os.Bundle c(android.os.Bundle)(:7)
       at com.android.installreferrer.api.InstallReferrerClientImpl.com.android.installreferrer.api.ReferrerDetails getInstallReferrer()(:26)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.void handleOnInstallReferrerSetupFinished(int)(:76)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.void access$handleOnInstallReferrerSetupFinished(de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin,int)()
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.void onInstallReferrerSetupFinished(int)(:2)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(:25)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2096)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2129)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:231)
       at android.os.Looper.loop(Looper.java:338)
       at android.app.ActivityThread.main(ActivityThread.java:8065)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:579)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by kartikcy** [comment]
Did we find any reason/solution for this ? Getting the same error across production release. I have made sure that installReferrer is called only once when the user is under authentication process. Can this happen if a user has installed the app, but hasn't launched it or has launched it but not logged in and closed the app, will that cause the referral data to be lost and when the user finally tries to login the referralData will not be found and dead object exception will be thrown ?

**Comment by lschmierer** [comment]
Even if the referrer data got lost it should just return empty referrer and not throw an exception.

Do you have any information on the frequency this error occurs?
Is it all devices? Or what percentage? Any special brand? Some version information? Maybe android version or even installed Play framework?

Only thing I can imagine right now is that the connection somehow gets lost between lines
 https://github.com/lschmierer/android_play_install_referrer/blob/7870fc56a5746a8b197e9f2917e83bf886860256/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt#L71
 and
https://github.com/lschmierer/android_play_install_referrer/blob/7870fc56a5746a8b197e9f2917e83bf886860256/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt#L82

We could maybe check in `handleOnInstallReferrerSetupFinished` if the connection is actually ready and maybe try again if not.

**Comment by kartikcy** [comment]
Thought so, even if the data is unavailable shouldn't cause a dead object exception. 
As per the logs from play console this is the stacktrace:

Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:575)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1090)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:565)
Caused by android.os.DeadObjectException:
  at android.os.BinderProxy.transactNative
  at android.os.BinderProxy.transact (BinderProxy.java:639)
  at com.google.android.a.a.b (BaseProxy.java:9)
  at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c (IGetInstallReferrerService.java:8)
  at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:1)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.kt:77)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.access$handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.kt:1)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.onInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.kt:3)
  at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:2280)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:2313)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:222)
  at android.os.Looper.loop (Looper.java:314)
  at android.app.ActivityThread.main (ActivityThread.java:8742)

Mostly seen on these devices: Some versions of Vivo (2132, V2308, V2327), Motorola lyriq, Oppo op56edl1, Redmi air. Along with that sdk 34 is where it happens the most (~90%), at least in my case. I already have a standard try-catch block where I create the install referrer instance but that apparently doesn't prevent the crash. Frequency of crashes is low, 17 total crash events in last 30 days.

**Comment by levBerlinkov** [comment]
Hi, we have same Crash in production:
Device: Oppo A93, Android 12

I just dropped PR to fix it, please check @lschmierer

**Comment by Its-KK** [comment]
> Even if the referrer data got lost it should just return empty referrer and not throw an exception.
> 
> Do you have any information on the frequency this error occurs? Is it all devices? Or what percentage? Any special brand? Some version information? Maybe android version or even installed Play framework?
> 
> Only thing I can imagine right now is that the connection somehow gets lost between lines
> 
> [android_play_install_referrer/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt](https://github.com/lschmierer/android_play_install_referrer/blob/7870fc56a5746a8b197e9f2917e83bf886860256/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt#L71)
> 
> Line 71 in [7870fc5](/lschmierer/android_play_install_referrer/commit/7870fc56a5746a8b197e9f2917e83bf886860256)
> 
>  override fun onInstallReferrerSetupFinished(responseCode: Int) { 
> 
> and
> [android_play_install_referrer/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt](https://github.com/lschmierer/android_play_install_referrer/blob/7870fc56a5746a8b197e9f2917e83bf886860256/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt#L82)
> 
> Line 82 in [7870fc5](/lschmierer/android_play_install_referrer/commit/7870fc56a5746a8b197e9f2917e83bf886860256)
> 
>  private fun handleOnInstallReferrerSetupFinished(responseCode: Int) { 
> We could maybe check in `handleOnInstallReferrerSetupFinished` if the connection is actually ready and maybe try again if not.

--
<details open><summary>Code sample</summary>

```dart
Future<void> _initializeInstallReferrer() async {
  try {
    if (Platform.isAndroid) {
      final box = GetStorage();
      bool isFirstLaunch = box.read('isFirstLaunch') ?? true;
      final referrerDetails = await AndroidPlayInstallReferrer.installReferrer;

      if (isFirstLaunch) {
        final referrerUrl = referrerDetails.installReferrer ?? '';
        // final clickTimestamp = referrerDetails.referrerClickTimestampSeconds;
        // final installTimestamp = referrerDetails.installBeginTimestampSeconds;

        if (referrerUrl.isNotEmpty) {
          final referrerParts = referrerUrl.split("&");

          final String utmSource =
              _extractReferrerParam(referrerParts, "utm_source=");
          final String utmMedium =
              _extractReferrerParam(referrerParts, "utm_medium=");
          final String utmCampaign =
              _extractReferrerParam(referrerParts, "utm_campaign=");
          final String utmContent =
              _extractReferrerParam(referrerParts, "utm_content=");
          final String referralCode =
              _extractReferrerParam(referrerParts, "referralCode=");

          final box = GetStorage();
          box.write('utm_source', utmSource);
          box.write('utm_medium', utmMedium);
          box.write('utm_campaign', utmCampaign);
          box.write('utm_content', utmContent);

          if (referralCode.isNotEmpty) {
            final referralController = Get.find<ReferralController>();
            referralController.setReferralCode(referralCode);
          }
        }
      }
    }
  } catch (e) {
    debugPrint('Error initializing Play Install Referrer: $e');
  }
}

```
</details>

<details open><summary>Crash Details</summary>

```dart
com.google.android.a.a.b
android.os.DeadObjectException

Sample attributes:
[Oppo CPH2239]
[Android 10 (SDK 29)]
Type : java.lang.RuntimeException

Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:522)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1027)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:512)
Caused by android.os.DeadObjectException:
  at android.os.BinderProxy.transactNative
  at android.os.BinderProxy.transact (BinderProxy.java:538)
  at com.google.android.a.a.b (a.java:2)
  at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c (IGetInstallReferrerService.java:3)
  at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:5)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.java:86)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.access$handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.java:17)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.onInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.java:72)
  at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java:4)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:2132)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:2164)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:240)
  at android.app.ActivityThread.main (ActivityThread.java:7829)
```

</details>

<details open><summary>Code sample</summary>

```dart
Sample attributes:
[Redmi Redmi 10C]
[Android 11 (SDK 30)]

Type : java.lang.RuntimeException

Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:666)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
Caused by android.os.DeadObjectException:
  at android.os.BinderProxy.transactNative
  at android.os.BinderProxy.transact (BinderProxy.java:608)
  at com.google.android.a.a.b (a.java:2)
  at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c (IGetInstallReferrerService.java:3)
  at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:5)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.java:86)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.access$handleOnInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.java:17)
  at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.onInstallReferrerSetupFinished (AndroidPlayInstallReferrerPlugin.java:72)
  at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java:4)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1991)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:2023)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8163)


```

</details>

![Image](https://github.com/user-attachments/assets/72c54097-52cb-401d-99cf-0879db828c9d)
![Image](https://github.com/user-attachments/assets/a7966259-37d5-444b-b13d-7450bb2c7e70)
![Image](https://github.com/user-attachments/assets/45f468dd-5274-4d92-a3ab-5fa3d6d0df0e)
![Image](https://github.com/user-attachments/assets/5102735c-6dd6-45db-9ad7-4c281e2a3031)

**Comment by JenyaKirmiza** [comment]
the same thing on my side

` Caused by android.os.DeadObjectException:
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:584)
       at com.google.android.a.a.b(a.java:2)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c(IGetInstallReferrerService.java:3)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:5)
       at com.eden_android.utils.referrer.InstallReferrerManager$fetchInstallReferrer$2$1$1.onInstallReferrerSetupFinished(InstallReferrerManager.java:32)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:4)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2207)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2240)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
        `

<img width="575" alt="Image" src="https://github.com/user-attachments/assets/71bf9ba9-1c57-4c21-b3c7-f3cc35b2e5e9" />

**Comment by Bohdandn** [comment]
Same issue, `Galaxy A16 5G, Android 14`. Slightly different stack trace:
```
          Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:598)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

          Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

          Caused by android.os.DeadObjectException:
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:662)
       at com.google.android.a.a.b(a.java:1)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c(IGetInstallReferrerService.java:1)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:1)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.handleOnInstallReferrerSetupFinished(AndroidPlayInstallReferrerPlugin.java:1)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin.access$handleOnInstallReferrerSetupFinished(AndroidPlayInstallReferrerPlugin.java:1)
       at de.lschmierer.android_play_install_referrer.AndroidPlayInstallReferrerPlugin$getInstallReferrer$1.onInstallReferrerSetupFinished(AndroidPlayInstallReferrerPlugin.java:1)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:1)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2348)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2385)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8934)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by JenyaKirmiza** [comment]
For some reason it is no longer reproducable in my case. I don't remember what exactly helped. Here you can see my code, maybe it's gonna help you. 

`import android.content.Context
import com.android.installreferrer.api.InstallReferrerClient
import com.android.installreferrer.api.InstallReferrerStateListener
import com.android.installreferrer.api.ReferrerDetails
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import timber.log.Timber

class InstallReferrerManager() {

    private suspend fun fetchInstallReferrer(context: Context): String? = withContext(Dispatchers.IO) {
        delay(2000L)
        val referrerClient = InstallReferrerClient.newBuilder(context).build()
        try {
            suspendCancellableCoroutine<String?> { continuation ->
                referrerClient.startConnection(object : InstallReferrerStateListener {
                    override fun onInstallReferrerSetupFinished(responseCode: Int) {
                        try {
                            when (responseCode) {
                                InstallReferrerClient.InstallReferrerResponse.OK -> {
                                    val response: ReferrerDetails = referrerClient.installReferrer
                                    val referrerUrl: String = response.installReferrer
                                    Timber.d("Referrer referrerUrl $referrerUrl")
                                    continuation.safeResume(referrerUrl) {}
                                }

                                else -> {
                                    continuation.safeResume(null) {}
                                }
                            }
                            referrerClient.endConnection()
                        } catch (e: Exception) {
                            e.printStackTrace()
                            if (e is CancellationException) throw e
                            continuation.safeResume(null) {}
                        }
                    }

                    override fun onInstallReferrerServiceDisconnected() {
                        // Optional: You could retry here if you want
                        try {
                            referrerClient.endConnection()
                        } catch (e: Exception) {
                            e.printStackTrace()
                            if (e is CancellationException) throw e
                        }
                    }
                })
            }
        } catch (e: Exception) {
            e.printStackTrace()
            if (e is CancellationException) throw e
            null
        }
    }

    fun initReferrer(context: Context){
        AppCoroutineScope.launch {
            runCatching {
                val referrer = withTimeoutOrNull(20000L) {
                    fetchInstallReferrer(context)
                }
                if (referrer != null) {
                    Timber.d("InstallReferrer Got referrer: %s", referrer)
                    // Save it or process it
                    runCatching {
                      // TODO
                        } else null
                    }.onFailure {
                        if (it is CancellationException) throw it
                    }
                } else {
                    Timber.d("InstallReferrer No referrer found")
                }
            }.onFailure {
                if (it is CancellationException) throw it
            }
        }
    }

}

object AppCoroutineScope : CoroutineScope by CoroutineScope(SupervisorJob() + Dispatchers.Default) {
    fun cancelScope() {
        coroutineContext.cancel()
    }
}

inline fun <T> Continuation<T>.safeResume(value: T, onExceptionCalled: () -> Unit) {
    if (this is CancellableContinuation) {
        if (isActive)
            resume(value)
        else
            onExceptionCalled()
    } else throw Exception("Must use suspendCancellableCoroutine instead of suspendCoroutine")
}
`
